version: '1.0'
files:
  TH1-ref.stp:
    parameters:
      L1:
        description: top_inner_y
        value: 0.4060330445686443
        min: 0.1
        max: 2.0
      L2:
        description: top_outer_y
        value: 1.9235604350851843
        min: 0.1
        max: 2.0
      L3:
        description: top_z
        value: 1.3966635883561136
        min: 0.1
        max: 2.0
      L4:
        description: upper_step_y
        value: 0.8000915416846294
        min: 0.1
        max: 1.0
      L5:
        description: outer_y
        value: 1.3169872993030947
        min: 0.1
        max: 2.0
      L6:
        description: outer_z
        value: 0.7152785546126982
        min: 0.1
        max: 2.0
      L7:
        description: lower_step_z
        value: 0.3072901309938114
        min: 0.1
        max: 2.0
      L8:
        description: inner_shelf_y
        value: 0.2791110960718911
        min: 0.1
        max: 2.0
      L9:
        description: inner_shelf_z
        value: 0.9701224450551476
        min: 0.1
        max: 1.5
      L10:
        description: bottom_z
        value: 0.7486096739002936
        min: 0.3
        max: 3.0
      R1:
        description: fillet_inner
        value: 0.05968799887455478
        min: 0.05
        max: 0.5
      R2:
        description: fillet_bottom
        value: 0.19758303182315423
        min: 0.05
        max: 0.5
    constraints:
      min_thickness: 0.2
