version: '1.0'
files:
  TH1-ref.stp:
    parameters:
      L1:
        description: top_inner_y
        value: 0.775
        min: 0.1
        max: 2.0
      L2:
        description: top_outer_y
        value: 0.85
        min: 0.1
        max: 2.0
      L3:
        description: top_z
        value: 0.943
        min: 0.1
        max: 2.0
      L4:
        description: upper_step_y
        value: 0.368
        min: 0.1
        max: 1.0
      L5:
        description: outer_y
        value: 0.775
        min: 0.1
        max: 2.0
      L6:
        description: outer_z
        value: 0.619
        min: 0.1
        max: 2.0
      L7:
        description: lower_step_z
        value: 0.631
        min: 0.1
        max: 2.0
      L8:
        description: inner_shelf_y
        value: 0.657
        min: 0.1
        max: 2.0
      L9:
        description: inner_shelf_z
        value: 0.698
        min: 0.1
        max: 1.5
      L10:
        description: bottom_z
        value: 0.3
        min: 0.3
        max: 3.0
      R1:
        description: fillet_inner
        value: 0.25
        min: 0.0
        max: 0.5
      R2:
        description: fillet_bottom
        value: 0.2
        min: 0.0
        max: 0.5
    constraints:
      min_thickness: 0.2
      anchors:
        outer_right_y: 2.75
        outer_top_z: 2.65
        shelf_inner_y: 0.6
        shelf_z: 1.7438
        origin_y: 0.0
        origin_z: 0.0
